version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:3.0-sdk
    steps:
      - checkout
      - run:
          name: Install Cake
          command: |
            dotnet tool install -g Cake.Tool
            echo 'export PATH=$PATH:/root/.dotnet/tools' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build
          command: dotnet cake build.cake --runtime=linux-x64
      - run:
          name: Deploy
          command: scp -o StrictHostKeyChecking=no -r /root/project/publish/* root@guardian-waf.com://applications/guardianui/
      - run:
          name: Service Restart
          command: ssh root@guardian-waf.com systemctl restart guardianui.service