// <auto-generated />
using System;
using Guardian.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Guardian.Infrastructure.Migrations
{
    [DbContext(typeof(GuardianDataContext))]
    partial class GuardianDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Guardian.Infrastructure.Entity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Email")
                        .HasMaxLength(200);

                    b.Property<string>("FullName")
                        .HasMaxLength(50);

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Guardian.Infrastructure.Entity.Target", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Domain")
                        .HasMaxLength(250);

                    b.Property<Guid>("AccountId");

                    b.Property<string>("CertCrt");

                    b.Property<string>("CertKey");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("OriginIpAddress")
                        .HasMaxLength(250);

                    b.HasKey("Id", "Domain");

                    b.HasIndex("AccountId");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("Guardian.Infrastructure.Entity.Target", b =>
                {
                    b.HasOne("Guardian.Infrastructure.Entity.Account", "Account")
                        .WithMany("Targets")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
